export const mockFinanceData = {
  by: "default",
  valid_key: true,
  results: {
    currencies: {
      source: "BRL",
      USD: {
        name: "Dollar",
        buy: 5.6012,
        sell: 5.6034,
        variation: -0.189,
      },
      EUR: {
        name: "Euro",
        buy: 6.282,
        sell: 6.2893,
        variation: 0.08,
      },
      GBP: {
        name: "Pound Sterling",
        buy: 7.4551,
        sell: null,
        variation: -0.153,
      },
      ARS: {
        name: "Argentine Peso",
        buy: 0.0047,
        sell: null,
        variation: 0,
      },
      CAD: {
        name: "Canadian Dollar",
        buy: 4.0101,
        sell: null,
        variation: -0.375,
      },
      AUD: {
        name: "Australian Dollar",
        buy: 3.6142,
        sell: null,
        variation: -0.435,
      },
      JPY: {
        name: "Japanese Yen",
        buy: 0.0382,
        sell: null,
        variation: 0.792,
      },
      CNY: {
        name: "Renminbi",
        buy: 0.7768,
        sell: null,
        variation: -0.206,
      },
      BTC: {
        name: "Bitcoin",
        buy: 616719.761,
        sell: 616719.761,
        variation: -0.381,
      },
    },
    stocks: {
      IBOVESPA: {
        name: "BM&F BOVESPA",
        location: "Sao Paulo, Brazil",
        points: 138979.48,
        variation: 0.01,
      },
      IFIX: {
        name: "Índice de Fundos de Investimentos Imobiliários B3",
        location: "Sao Paulo, Brazil",
        points: 3411.59,
        variation: 0,
      },
      NASDAQ: {
        name: "NASDAQ Stock Market",
        location: "New York City, United States",
        points: 19061.18,
        variation: 0.27,
      },
      DOWJONES: {
        name: "Dow Jones Industrial Average",
        location: "New York City, United States",
        points: 42172.64,
        variation: 0.08,
      },
      CAC: {
        name: "CAC 40",
        location: "Paris, French",
        points: 7830.76,
        variation: -0.55,
      },
      NIKKEI: {
        name: "Nikkei 225",
        location: "Tokyo, Japan",
        points: 38128.13,
        variation: -0.14,
      },
    },
    available_sources: ["BRL"],
    bitcoin: {
      blockchain_info: {
        name: "Blockchain.info",
        format: ["USD", "en_US"],
        last: 103872.58,
        buy: 103872.58,
        sell: 103872.58,
        variation: -0.381,
      },
      bitstamp: {
        name: "BitStamp",
        format: ["USD", "en_US"],
        last: 103815,
        buy: 103839,
        sell: 103835,
        variation: -0.607,
      },
      foxbit: {
        name: "FoxBit",
        format: ["BRL", "pt_BR"],
        last: 582841,
        variation: -0.651,
      },
      mercadobitcoin: {
        name: "Mercado Bitcoin",
        format: ["BRL", "pt_BR"],
        last: 582522,
        buy: 582586,
        sell: 582935,
        variation: -0.763,
      },
    },
    taxes: [
      {
        date: "2025-05-08",
        cdi: 14.75,
        selic: 14.75,
        daily_factor: 1.00054266,
        selic_daily: 14.65,
        cdi_daily: 14.65,
      },
    ],
  },
  execution_time: 0,
  from_cache: true,
};
